package main

// DO NOT EDIT, this file is generated by hover at compile-time for the fijkplayer plugin.

import (
	fijkplayer "github.com/befovy/fijkplayer/go"
	"github.com/go-flutter-desktop/go-flutter"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&fijkplayer.FijkplayerPlugin{}))
}
